# Generated by Django 5.1.4 on 2025-01-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installment',
            old_name='due_date',
            new_name='estimated_date',
        ),
        migrations.AddField(
            model_name='installment',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='installment',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installment',
            name='observation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
