# Generated by Django 5.1.4 on 2025-01-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_due_date_installment_estimated_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='areas',
            field=models.ManyToManyField(through='projects.ProjectArea', to='projects.area'),
        ),
    ]
