# Generated by Django 5.1.4 on 2025-01-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_areas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='areas',
        ),
        migrations.AddField(
            model_name='area',
            name='projects',
            field=models.ManyToManyField(through='projects.ProjectArea', to='projects.project'),
        ),
    ]
