# Generated by Django 5.1.4 on 2025-01-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_areas_area_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='areas',
            field=models.ManyToManyField(through='projects.ProjectArea', to='projects.area'),
        ),
    ]
