# Generated by Django 5.1.4 on 2025-02-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_nota_dotacao_alter_project_ptres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='detailed_nature',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='funding_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='internal_plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='internal_plan_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
